#!/usr/bin/env bash

# check we are using a screen session
if [ -z ${STY} ];
  then
    echo "Use screen session please, \`screen -ls\`"
    exit 1;
  else
    # define port from screen sessionName
    echo "Checking your port out"
    mongo_port=$(echo $STY | sed -e 's/.*\.mongo\.//');
fi

# 3 member set set-up, ports tied to sets
case $mongo_port in
  *[^0-9]*) 
    echo "Port is not an integer"
    exit 1;;
  "27017")
    replica_set=0;;
  "27018")
    replica_set=1;;
  "27019")
    replica_set=2;;
esac

# make sure the port is set
if [ -z ${replica_set} ]
  then
    echo "Invalid Port use"
    echo "Consider 27017, 27018, 27019 in the right named screen session: \`screen -ls\`"
    exit 1
fi

echo "Running mongod... "
echo "mongod --port $mongo_port --dbpath /srv/mongodb/rs0-${replica_set} --replSet rs0 --smallfiles --oplogSize 128 --keyFile '/srv/mongodb/keyfile'"

mongod --port $mongo_port \
  --dbpath /srv/mongodb/rs0-${replica_set} \
  --replSet rs0 \
  --smallfiles \
  --oplogSize 128 \
  --keyFile '/srv/mongodb/keyfile'


