#!/usr/bin/env bash

# check we are using a screen session
if [ -z ${STY} ];
  then
    echo "Use screen session please, \`screen -ls\`"
    exit 1;
  else
    # define port from screen sessionName
    echo "Checking your port out"
    MONGO_PORT=$(echo $STY | sed -e 's/.*\.mongo\.//');
fi

# 3 member set set-up, ports tied to sets
case $MONGO_PORT in
  *[^0-9]*) 
    echo "Port is not an integer"
    exit 1;;
  "27017")
    REPLICA_SET=0;;
  "27018")
    REPLICA_SET=1;;
  "27019")
    REPLICA_SET=2;;
esac

# make sure the port is set
if [ -z ${REPLICA_SET} ]
  then
    echo "Invalid Port use"
    echo "Consider 27017, 27018, 27019 in the right named screen session: \`screen -ls\`"
    exit 1
fi

echo "Running mongod... "
echo "mongod --port $MONGO_PORT --dbpath /srv/mongodb/rs0-${REPLICA_SET} --replSet rs0 --smallfiles --oplogSize 128"
mongod --port $MONGO_PORT --dbpath /srv/mongodb/rs0-${REPLICA_SET} --replSet rs0 --smallfiles --oplogSize 128

